server:
  port: 4000

spring:
  application:
    name: atguigu-consumer

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:5000/eureka

  instance:
    instance-id: consumer-4000
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true