spring:
  application:
    name: atguigu-provider
server:
  port: 2000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:5000/eureka
  instance:
       instance-id: 2000
       prefer-ip-address: true


management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream