server:
  port: 1000
spring:
  application:
    name: atguigu-provider

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:5000/eureka
  instance:
    instance-id: 1000
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream